//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedToDo
    {
        public int Id { get; set; }
        public string SharedTo { get; set; }
        public string SharedBy { get; set; }
        public Nullable<int> ToDoId { get; set; }
    
        public virtual ToDo ToDo { get; set; }
    }
}
