//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToDo()
        {
            this.Tasks = new HashSet<Task>();
            this.SharedToDoes = new HashSet<SharedToDo>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatorId { get; set; }
        public System.DateTime LastChanged { get; set; }
        public int LastChangedUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharedToDo> SharedToDoes { get; set; }
    }
}
